In [2]:
# Import the Pandas library
import pandas as pd

In [3]:
# File to load
# Create a reference the CSV file desired
df = pd.read_csv('pokemon.csv')
# Read the CSV into a Pandas DataFrame

# Print the first five rows of data to the screen
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [ ]:
# Read with Pandas

In [16]:
# Extract the following columns: "Type 1", "HP", "Attack", "Sp. Atk", "Sp. Def", and "Speed"
new_df = df[['Type 1','HP', 'Attack', 'Sp. Atk', 'Sp. Def', 'Speed']]
new_df.head(5)

  Type 1  HP  Attack  Sp. Atk  Sp. Def  Speed
0  Grass  45      49       65       65     45
1  Grass  60      62       80       80     60
2  Grass  80      82      100      100     80
3  Grass  80     100      122      120     80
4   Fire  39      52       60       50     65

In [33]:
# Create a dataframe of the average stats for each type of pokemon.
type_df = new_df.groupby(['Type 1']).mean()
type_df.head(5)

                 HP      Attack    Sp. Atk    Sp. Def      Speed
Type 1
Bug       56.884058   70.971014  53.869565  64.797101  61.681159
Dark      66.806452   88.387097  74.645161  69.516129  76.161290
Dragon    83.312500  112.125000  96.843750  88.843750  83.031250
Electric  59.795455   69.090909  90.022727  73.704545  84.500000
Fairy     74.117647   61.529412  78.529412  84.705882  48.588235

In [36]:
# Calculate the total power level of each type of pokemon by adding all of the stats together.
# Place the results into a new column.
new_df['Total Power'] = new_df['Attack'] + new_df['Sp. Atk']+ new_df['Sp. Def']+ new_df['Speed']
new_df

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

       Type 1   HP  Attack  Sp. Atk  Sp. Def  Speed  Total Power
0       Grass   45      49       65       65     45          224
1       Grass   60      62       80       80     60          282
2       Grass   80      82      100      100     80          362
3       Grass   80     100      122      120     80          422
4        Fire   39      52       60       50     65          227
5        Fire   58      64       80       65     80          289
6        Fire   78      84      109       85    100          378
7        Fire   78     130      130       85    100          445
8        Fire   78     104      159      115    100          478
9       Water   44      48       50       64     43          205
10      Water   59      63       65       80     58          266
11      Water   79      83       85      105     78          351
12      Water   79     103      135      115     78          431
13        Bug   45      30       20       20     45          115
14        Bug   50      20       25       25     30          100
15        Bug   60      45       90       80     70          285
16        Bug   40      35       20       20     50          125
17        Bug   45      25       25       25     35          110
18        Bug   65      90       45       80     75          290
19        Bug   65     150       15       80    145          390
20     Normal   40      45       35       35     56          171
21     Normal   63      60       50       50     71          231
22     Normal   83      80       70       70    101          321
23     Normal   83      80      135       80    121          416
24     Normal   30      56       25       35     72          188
25     Normal   55      81       50       70     97          298
26     Normal   40      60       31       31     70          192
27     Normal   65      90       61       61    100          312
28     Poison   35      60       40       54     55          209
29     Poison   60      85       65       79     80          309
..        ...  ...     ...      ...      ...    ...          ...
770     Fairy   95      65      110      130     60          365
771  Fighting   78      92       74       63    118          347
772  Electric   67      58       81       67    101          307
773      Rock   50      50       50      150     50          300
774    Dragon   45      50       55       75     40          220
775    Dragon   68      75       83      113     60          331
776    Dragon   90     100      110      150     80          440
777     Steel   57      80       80       87     75          322
778     Ghost   43      70       50       60     38          218
779     Ghost   85     110       65       82     56          313
780     Ghost   49      66       44       55     51          216
781     Ghost   44      66       44       55     56          221
782     Ghost   54      66       44       55     46          211
783     Ghost   59      66       44       55     41          206
784     Ghost   65      90       58       75     84          307
785     Ghost   55      85       58       75     99          317
786     Ghost   75      95       58       75     69          297
787     Ghost   85     100       58       75     54          287
788       Ice   55      69       32       35     28          164
789       Ice   95     117       44       46     28          235
790    Flying   40      30       45       40     55          170
791    Flying   85      70       97       80    123          370
792     Fairy  126     131      131       98     99          459
793      Dark  126     131      131       98     99          459
794    Dragon  108     100       81       95     95          371
795      Rock   50     100      100      150     50          400
796      Rock   50     160      160      110    110          540
797   Psychic   80     110      150      130     70          460
798   Psychic   80     160      170      130     80          540
799      Fire   80     110      130       90     70          400

[800 rows x 7 columns]

In [39]:
# Bonus: Sort the table by strongest type and export the resulting table to a new CSV.
strongest_pokemon = new_df.sort_values(["Total Power"], ascending=False)
strongest_pokemon.reset_index(inplace=True)
strongest_pokemon

     index    Type 1   HP  Attack  Sp. Atk  Sp. Def  Speed  Total Power
0      164   Psychic  106     150      194      120    140          604
1      422     Water  100     150      180      160     90          580
2      426    Dragon  105     180      180      100    115          575
3      163   Psychic  106     190      154      100    130          574
4      796      Rock   50     160      160      110    110          540
5      798   Psychic   80     160      170      130     80          540
6      429   Psychic   50     180      180       20    150          530
7      420    Dragon   80     130      160      120    110          520
8      424    Ground  100     180      150       90     90          510
9      418    Dragon   80     100      140      150    110          500
10     428   Psychic   50     150      150       50    150          500
11     541     Water   90     120      150      120    100          490
12     275     Grass   70     110      145       85    145          485
13     712    Dragon  125     120      170      100     95          485
14     306   Psychic   68      85      165      135    100          485
15     425    Dragon  105     150      150       90     95          485
16     162   Psychic  106     110      154       90    130          484
17     270      Fire  106     130      110      154     90          484
18     706    Dragon  100     120      150      120     90          480
19     552    Normal  120     120      120      120    120          480
20     421     Water  100     100      150      140     90          480
21       8      Fire   78     104      159      115    100          478
22     494    Dragon  108     170      120       95     92          477
23     409    Dragon   95     145      120       90    120          475
24     711    Dragon  125     170      120       90     95          475
25      71   Psychic   55      50      175       95    150          470
26     413     Steel   80     145      105      110    110          470
27     279      Fire   80     160      130       80    100          470
28     498  Fighting   70     145      140       70    112          467
29     102     Ghost   60      65      170       95    130          460
..     ...       ...  ...     ...      ...      ...    ...          ...
770    175    Normal   35      46       35       45     20          146
771    303   Psychic   28      25       45       35     40          145
772    486      Rock   50      80       10       45     10          145
773    314       Bug   31      45       30       30     40          145
774    189     Fairy   35      20       40       65     20          145
775    255  Fighting   35      35       35       35     35          140
776    187     Fairy   50      25       45       55     15          140
777    583      Rock   55      75       25       25     15          140
778    457       Bug   40      29       29       45     36          139
779    320  Fighting   72      60       20       30     25          135
780     44    Normal  115      45       45       25     20          135
781    198     Water   70      20       20       50     40          130
782    296     Grass   40      40       30       30     30          130
783    139     Water   20      10       15       20     80          125
784     16       Bug   40      35       20       20     50          125
785    732       Bug   38      35       27       25     35          122
786    206     Grass   30      30       30       30     30          120
787    394   Psychic   95      23       23       48     23          117
788    446       Bug   37      25       25       41     25          116
789     13       Bug   45      30       20       20     45          115
790    488    Normal  100       5       15       65     30          115
791    288       Bug   45      45       20       30     20          115
792    209     Water   55      45       25       25     15          110
793     17       Bug   45      25       25       25     35          110
794    733       Bug   45      22       27       30     29          108
795    188    Normal   90      30       40       20     15          105
796    322    Normal   50      20       20       40     20          100
797     14       Bug   50      20       25       25     30          100
798    291       Bug   50      35       25       25     15          100
799    289       Bug   50      35       25       25     15          100

[800 rows x 8 columns]

In [41]:
new_df.to_excel("pokemon_rankings.xlsx", index=False)